### ISSUE TITLE
Implement stress spherical harmonics expansion

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/napari-stress#36]
I also implemented the spherical harmonics expansion from the original stress repository and the expansion performs notably better. I'm not sure as to what the reason for this is - I'll create an issue at shtools for this. 

However, I think we should put this implementation in this repository, too, in order to stay close to the original method. Caveat: This stuff is potentially unreviewable.

I have a working version of both implementations on [this branch](https://github.com/BiAPoL/napari-stress/tree/spherical-harmonics-surface-fit). The desired implementation can be chosen with a dropdown in the Napari widget.

@haesleinhuepf what do you think?

**Comment by haesleinhuepf** [comment]
This was solved in #51, correct @jo-mueller ?
