### ISSUE TITLE
Author list

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-stress#60]
Hi Johannes @jo-mueller ,

could you please check and confirm that the author-list as specified on pypi and the napari hub fully reflects the authors of the code.
https://github.com/BiAPoL/napari-stress/blob/main/setup.cfg#L4

I could imagine that there is some code in [this folder](https://github.com/BiAacPoL/napari-stress/tree/main/src/napari_stress/_spherical_harmonics) where you are not the author. Consider listing the original authors in the author list.

Thanks!

Best,
Robert

**Comment by jo-mueller** [comment]
Hi @carlos-gomez00 , @campaslab, @ElijahShelton, @GrossBJ:

I would like to add you as authors of this plugin. This would be displayed

- here on the Github repository
- on the [napari hub](https://www.napari-hub.org/plugins/napari-stress)

If you agree, let me know and I'll make the necessary changes :)

**Comment by GrossBJ** [comment]
Of course, thanks Johannes!

Ben J. Gross 
 
  El vie, 3 de jun. de 2022 a la(s) 7:38, Johannes ***@***.***> escribió:   


Hi @carlos-gomez00 , @campaslab, @ElijahShelton, @GrossBJ:

I would like to add you as authors of this plugin. This would be displayed
   
   - here on the Github repository
   - on the napari hub

If you agree, let me know and I'll make the necessary changes :)

**Comment by ElijahShelton** [comment]
Of course! Happy to see this plugin in the world.

**Comment by campaslab** [comment]
Yes, thanks a lot Johannes!

Otger

**Comment by carlos-gomez00** [comment]
Yup thanks!
